// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SistemaSocios.WebApi.MySqlN.Migrations
{
    [DbContext(typeof(DbMySqlContext))]
    [Migration("20240405140421_xis005")]
    partial class xis005
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnderecoUsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TipoEnderecoUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TipoEnderecoUsuarioId");

                    b.HasIndex("UsuarioID");

                    b.ToTable("EnderecoUsuario");
                });

            modelBuilder.Entity("EntidadeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescricaoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Entidades", (string)null);
                });

            modelBuilder.Entity("EscolaridadeUsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescricaoEscolaridade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("EscolaridadeUsuario");
                });

            modelBuilder.Entity("HistoricoMensalidadesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusMensalidadeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("HistoricoMensalidades", (string)null);
                });

            modelBuilder.Entity("JurosMensalidadeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataVigenciaJuros")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("statusValorJuros")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("valorJuros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JurosMensalidade");
                });

            modelBuilder.Entity("RedeSocialModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoRedeSocialUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlRedeSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("RedeSocial");
                });

            modelBuilder.Entity("TelefoneUsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DddTelefoneUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefoneUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TipoTelefoneUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TipoTelefoneUsuarioId");

                    b.ToTable("TelefoneUsuario");
                });

            modelBuilder.Entity("TipoEnderecoUsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TipoEnderecoUsuario");
                });

            modelBuilder.Entity("TipoTelefoneUsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TipoTelefoneUsuario");
                });

            modelBuilder.Entity("UsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIniciacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaObrigacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EscolaridadeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JurosMensalidadeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MensalidadeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RedeSocialId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ValorMensalidadeId")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ValorMensalidadeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ValorMensalidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("VigenciaMensalidade")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("statusValorMensalidade")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ValorMensalidade");
                });

            modelBuilder.Entity("perfilModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescricaoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("EnderecoUsuarioModel", b =>
                {
                    b.HasOne("TipoEnderecoUsuarioModel", "TipoEndereco")
                        .WithMany("Enderecos")
                        .HasForeignKey("TipoEnderecoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EnderecoUsuario_TipoEnderecoUsuario_TipoEnderecoId");

                    b.HasOne("UsuarioModel", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEndereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EntidadeModel", b =>
                {
                    b.HasOne("UsuarioModel", null)
                        .WithOne("Entidade")
                        .HasForeignKey("EntidadeModel", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EscolaridadeUsuarioModel", b =>
                {
                    b.HasOne("UsuarioModel", null)
                        .WithOne("Escolaridade")
                        .HasForeignKey("EscolaridadeUsuarioModel", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HistoricoMensalidadesModel", b =>
                {
                    b.HasOne("UsuarioModel", null)
                        .WithMany("HistoricoMensalidades")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JurosMensalidadeModel", b =>
                {
                    b.HasOne("UsuarioModel", null)
                        .WithMany("AplicaJurosMensalidade")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RedeSocialModel", b =>
                {
                    b.HasOne("UsuarioModel", null)
                        .WithMany("RedesSociais")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TelefoneUsuarioModel", b =>
                {
                    b.HasOne("TipoTelefoneUsuarioModel", "TipoTelefone")
                        .WithMany()
                        .HasForeignKey("TipoTelefoneUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UsuarioModel", null)
                        .WithMany("Telefones")
                        .HasForeignKey("TipoTelefoneUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoTelefone");
                });

            modelBuilder.Entity("ValorMensalidadeModel", b =>
                {
                    b.HasOne("UsuarioModel", "Usuario")
                        .WithMany("ValorMensalidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("perfilModel", b =>
                {
                    b.HasOne("UsuarioModel", null)
                        .WithOne("PerfilAcesso")
                        .HasForeignKey("perfilModel", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TipoEnderecoUsuarioModel", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("UsuarioModel", b =>
                {
                    b.Navigation("AplicaJurosMensalidade");

                    b.Navigation("Enderecos");

                    b.Navigation("Entidade")
                        .IsRequired();

                    b.Navigation("Escolaridade")
                        .IsRequired();

                    b.Navigation("HistoricoMensalidades");

                    b.Navigation("PerfilAcesso")
                        .IsRequired();

                    b.Navigation("RedesSociais");

                    b.Navigation("Telefones");

                    b.Navigation("ValorMensalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
