name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

      - name: Build the project
        run: dotnet build -c Release

      - name: Publish the project
        run: dotnet publish -c Release -o ./publish

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
