name: Deploy .NET Core Application to GitHub Pages

on:
  push:
    branches: ["main"]  # Troque para a branch que deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'  # Altere para a versão do .NET Core que você está usando
      
      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o ./publish
          echo '.nojekyll' > ./publish/.nojekyll

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          cname: example.com  # Substitua pelo seu domínio personalizado (se aplicável)
          commit_message: Deploying .NET Core application to GitHub Pages
          allow_empty_commit: true
          force_orphan: true
